# -*- coding: utf-8 -*-
"""Milad-Data-Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yCxxoXR5j6V1BqPBMZamaRaxbFvX4u3R
"""

import pandas as pd
import numpy as np

csv_file_path = ""
df = pd.read_csv(csv_file_path, sep=" ", header=None)

# Drop any extra columns created due to trailing spaces
df.dropna(axis=1, how='all', inplace=True)

# ADD Column Name
df.columns = ['ID', 'Cycle', 'OpSet1', 'OpSet2', 'OpSet3', 'SensorMeasure1', 'SensorMeasure2', 'SensorMeasure3', 'SensorMeasure4', 'SensorMeasure5', 'SensorMeasure6', 'SensorMeasure7', 'SensorMeasure8', 'SensorMeasure9', 'SensorMeasure10', 'SensorMeasure11', 'SensorMeasure12', 'SensorMeasure13', 'SensorMeasure14', 'SensorMeasure15', 'SensorMeasure16', 'SensorMeasure17', 'SensorMeasure18', 'SensorMeasure19', 'SensorMeasure20', 'SensorMeasure21']

# Calcualte End of Life
EOL=[]
for sl_no in df['ID']:
        EOL.append( ((df[df['ID'] == sl_no]["Cycle"]).values)[-1])
#
df["EOL"]=EOL
df["LR"] = df["Cycle"].div(df["EOL"])

df=df.drop(columns=['ID','EOL'])

labels=[]
for i in range (0,len(df)):
    if np.array(df["LR"])[i] <= 0.6:
        labels.append(0)
    elif np.array(df["LR"])[i] <= 0.8 :
        labels.append(1)
    else :
        labels.append(2)

df["labels"]=labels
df  = df.drop(columns=['LR'])

df.to_csv('/content/train_FD001_cleaned.csv', index=False)